name: Atualizar Dados Legislativos

on:
  schedule:
    # Rodar às 6h da manhã (UTC) todos os dias, exceto durante os finais de semana
    - cron: "0 6 * * 1-5"
  workflow_dispatch:  # Permite disparar manualmente

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
      # Checkout do repositório
      - name: Checkout do código
        uses: actions/checkout@v3

      # Configurar Python
      - name: Configurar Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      # Instalar dependências
      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Executar script de atualização da Câmara
      - name: Atualizar dados da Câmara
        run: python update-camara.py

      # Executar script de atualização do Senado
      - name: Atualizar dados do Senado
        run: python update-senado.py

      # Commit e push dos arquivos atualizados
      - name: Commit e push dos arquivos atualizados
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add data-json/dados_camara.json data-json/dados_senado.json
          git commit -m "Atualização diária dos dados legislativos"
          git push
